// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/people.proto

package com.auth0.protobuf;

public final class PeopleOuterClass {
  private PeopleOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PeopleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.People)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .demo.Person person = 1;</code>
     */
    java.util.List<com.auth0.protobuf.PeopleOuterClass.Person> 
        getPersonList();
    /**
     * <code>repeated .demo.Person person = 1;</code>
     */
    com.auth0.protobuf.PeopleOuterClass.Person getPerson(int index);
    /**
     * <code>repeated .demo.Person person = 1;</code>
     */
    int getPersonCount();
    /**
     * <code>repeated .demo.Person person = 1;</code>
     */
    java.util.List<? extends com.auth0.protobuf.PeopleOuterClass.PersonOrBuilder> 
        getPersonOrBuilderList();
    /**
     * <code>repeated .demo.Person person = 1;</code>
     */
    com.auth0.protobuf.PeopleOuterClass.PersonOrBuilder getPersonOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code demo.People}
   */
  public  static final class People extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.People)
      PeopleOrBuilder {
    // Use People.newBuilder() to construct.
    private People(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private People() {
      person_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private People(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                person_ = new java.util.ArrayList<com.auth0.protobuf.PeopleOuterClass.Person>();
                mutable_bitField0_ |= 0x00000001;
              }
              person_.add(
                  input.readMessage(com.auth0.protobuf.PeopleOuterClass.Person.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = java.util.Collections.unmodifiableList(person_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.auth0.protobuf.PeopleOuterClass.internal_static_demo_People_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.auth0.protobuf.PeopleOuterClass.internal_static_demo_People_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.auth0.protobuf.PeopleOuterClass.People.class, com.auth0.protobuf.PeopleOuterClass.People.Builder.class);
    }

    public static final int PERSON_FIELD_NUMBER = 1;
    private java.util.List<com.auth0.protobuf.PeopleOuterClass.Person> person_;
    /**
     * <code>repeated .demo.Person person = 1;</code>
     */
    public java.util.List<com.auth0.protobuf.PeopleOuterClass.Person> getPersonList() {
      return person_;
    }
    /**
     * <code>repeated .demo.Person person = 1;</code>
     */
    public java.util.List<? extends com.auth0.protobuf.PeopleOuterClass.PersonOrBuilder> 
        getPersonOrBuilderList() {
      return person_;
    }
    /**
     * <code>repeated .demo.Person person = 1;</code>
     */
    public int getPersonCount() {
      return person_.size();
    }
    /**
     * <code>repeated .demo.Person person = 1;</code>
     */
    public com.auth0.protobuf.PeopleOuterClass.Person getPerson(int index) {
      return person_.get(index);
    }
    /**
     * <code>repeated .demo.Person person = 1;</code>
     */
    public com.auth0.protobuf.PeopleOuterClass.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(1, person_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.auth0.protobuf.PeopleOuterClass.People)) {
        return super.equals(obj);
      }
      com.auth0.protobuf.PeopleOuterClass.People other = (com.auth0.protobuf.PeopleOuterClass.People) obj;

      boolean result = true;
      result = result && getPersonList()
          .equals(other.getPersonList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getPersonCount() > 0) {
        hash = (37 * hash) + PERSON_FIELD_NUMBER;
        hash = (53 * hash) + getPersonList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.auth0.protobuf.PeopleOuterClass.People parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.auth0.protobuf.PeopleOuterClass.People parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.auth0.protobuf.PeopleOuterClass.People parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.auth0.protobuf.PeopleOuterClass.People parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.auth0.protobuf.PeopleOuterClass.People parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.auth0.protobuf.PeopleOuterClass.People parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.auth0.protobuf.PeopleOuterClass.People parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.auth0.protobuf.PeopleOuterClass.People parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.auth0.protobuf.PeopleOuterClass.People parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.auth0.protobuf.PeopleOuterClass.People parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.auth0.protobuf.PeopleOuterClass.People prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.People}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.People)
        com.auth0.protobuf.PeopleOuterClass.PeopleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.auth0.protobuf.PeopleOuterClass.internal_static_demo_People_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.auth0.protobuf.PeopleOuterClass.internal_static_demo_People_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.auth0.protobuf.PeopleOuterClass.People.class, com.auth0.protobuf.PeopleOuterClass.People.Builder.class);
      }

      // Construct using com.auth0.protobuf.PeopleOuterClass.People.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          personBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.auth0.protobuf.PeopleOuterClass.internal_static_demo_People_descriptor;
      }

      public com.auth0.protobuf.PeopleOuterClass.People getDefaultInstanceForType() {
        return com.auth0.protobuf.PeopleOuterClass.People.getDefaultInstance();
      }

      public com.auth0.protobuf.PeopleOuterClass.People build() {
        com.auth0.protobuf.PeopleOuterClass.People result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.auth0.protobuf.PeopleOuterClass.People buildPartial() {
        com.auth0.protobuf.PeopleOuterClass.People result = new com.auth0.protobuf.PeopleOuterClass.People(this);
        int from_bitField0_ = bitField0_;
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            person_ = java.util.Collections.unmodifiableList(person_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.auth0.protobuf.PeopleOuterClass.People) {
          return mergeFrom((com.auth0.protobuf.PeopleOuterClass.People)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.auth0.protobuf.PeopleOuterClass.People other) {
        if (other == com.auth0.protobuf.PeopleOuterClass.People.getDefaultInstance()) return this;
        if (personBuilder_ == null) {
          if (!other.person_.isEmpty()) {
            if (person_.isEmpty()) {
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePersonIsMutable();
              person_.addAll(other.person_);
            }
            onChanged();
          }
        } else {
          if (!other.person_.isEmpty()) {
            if (personBuilder_.isEmpty()) {
              personBuilder_.dispose();
              personBuilder_ = null;
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
              personBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPersonFieldBuilder() : null;
            } else {
              personBuilder_.addAllMessages(other.person_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.auth0.protobuf.PeopleOuterClass.People parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.auth0.protobuf.PeopleOuterClass.People) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.auth0.protobuf.PeopleOuterClass.Person> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = new java.util.ArrayList<com.auth0.protobuf.PeopleOuterClass.Person>(person_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.auth0.protobuf.PeopleOuterClass.Person, com.auth0.protobuf.PeopleOuterClass.Person.Builder, com.auth0.protobuf.PeopleOuterClass.PersonOrBuilder> personBuilder_;

      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public java.util.List<com.auth0.protobuf.PeopleOuterClass.Person> getPersonList() {
        if (personBuilder_ == null) {
          return java.util.Collections.unmodifiableList(person_);
        } else {
          return personBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public int getPersonCount() {
        if (personBuilder_ == null) {
          return person_.size();
        } else {
          return personBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public com.auth0.protobuf.PeopleOuterClass.Person getPerson(int index) {
        if (personBuilder_ == null) {
          return person_.get(index);
        } else {
          return personBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public Builder setPerson(
          int index, com.auth0.protobuf.PeopleOuterClass.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.set(index, value);
          onChanged();
        } else {
          personBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public Builder setPerson(
          int index, com.auth0.protobuf.PeopleOuterClass.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.set(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public Builder addPerson(com.auth0.protobuf.PeopleOuterClass.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(value);
          onChanged();
        } else {
          personBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public Builder addPerson(
          int index, com.auth0.protobuf.PeopleOuterClass.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(index, value);
          onChanged();
        } else {
          personBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public Builder addPerson(
          com.auth0.protobuf.PeopleOuterClass.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public Builder addPerson(
          int index, com.auth0.protobuf.PeopleOuterClass.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public Builder addAllPerson(
          java.lang.Iterable<? extends com.auth0.protobuf.PeopleOuterClass.Person> values) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, person_);
          onChanged();
        } else {
          personBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public Builder removePerson(int index) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.remove(index);
          onChanged();
        } else {
          personBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public com.auth0.protobuf.PeopleOuterClass.Person.Builder getPersonBuilder(
          int index) {
        return getPersonFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public com.auth0.protobuf.PeopleOuterClass.PersonOrBuilder getPersonOrBuilder(
          int index) {
        if (personBuilder_ == null) {
          return person_.get(index);  } else {
          return personBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public java.util.List<? extends com.auth0.protobuf.PeopleOuterClass.PersonOrBuilder> 
           getPersonOrBuilderList() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(person_);
        }
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public com.auth0.protobuf.PeopleOuterClass.Person.Builder addPersonBuilder() {
        return getPersonFieldBuilder().addBuilder(
            com.auth0.protobuf.PeopleOuterClass.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public com.auth0.protobuf.PeopleOuterClass.Person.Builder addPersonBuilder(
          int index) {
        return getPersonFieldBuilder().addBuilder(
            index, com.auth0.protobuf.PeopleOuterClass.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.Person person = 1;</code>
       */
      public java.util.List<com.auth0.protobuf.PeopleOuterClass.Person.Builder> 
           getPersonBuilderList() {
        return getPersonFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.auth0.protobuf.PeopleOuterClass.Person, com.auth0.protobuf.PeopleOuterClass.Person.Builder, com.auth0.protobuf.PeopleOuterClass.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.auth0.protobuf.PeopleOuterClass.Person, com.auth0.protobuf.PeopleOuterClass.Person.Builder, com.auth0.protobuf.PeopleOuterClass.PersonOrBuilder>(
                  person_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:demo.People)
    }

    // @@protoc_insertion_point(class_scope:demo.People)
    private static final com.auth0.protobuf.PeopleOuterClass.People DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.auth0.protobuf.PeopleOuterClass.People();
    }

    public static com.auth0.protobuf.PeopleOuterClass.People getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<People>
        PARSER = new com.google.protobuf.AbstractParser<People>() {
      public People parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new People(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<People> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<People> getParserForType() {
      return PARSER;
    }

    public com.auth0.protobuf.PeopleOuterClass.People getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .demo.Address address = 2;</code>
     */
    java.util.List<com.auth0.protobuf.PeopleOuterClass.Address> 
        getAddressList();
    /**
     * <code>repeated .demo.Address address = 2;</code>
     */
    com.auth0.protobuf.PeopleOuterClass.Address getAddress(int index);
    /**
     * <code>repeated .demo.Address address = 2;</code>
     */
    int getAddressCount();
    /**
     * <code>repeated .demo.Address address = 2;</code>
     */
    java.util.List<? extends com.auth0.protobuf.PeopleOuterClass.AddressOrBuilder> 
        getAddressOrBuilderList();
    /**
     * <code>repeated .demo.Address address = 2;</code>
     */
    com.auth0.protobuf.PeopleOuterClass.AddressOrBuilder getAddressOrBuilder(
        int index);

    /**
     * <code>repeated string mobile = 3;</code>
     */
    java.util.List<java.lang.String>
        getMobileList();
    /**
     * <code>repeated string mobile = 3;</code>
     */
    int getMobileCount();
    /**
     * <code>repeated string mobile = 3;</code>
     */
    java.lang.String getMobile(int index);
    /**
     * <code>repeated string mobile = 3;</code>
     */
    com.google.protobuf.ByteString
        getMobileBytes(int index);

    /**
     * <code>repeated string email = 4;</code>
     */
    java.util.List<java.lang.String>
        getEmailList();
    /**
     * <code>repeated string email = 4;</code>
     */
    int getEmailCount();
    /**
     * <code>repeated string email = 4;</code>
     */
    java.lang.String getEmail(int index);
    /**
     * <code>repeated string email = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes(int index);
  }
  /**
   * Protobuf type {@code demo.Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      address_ = java.util.Collections.emptyList();
      mobile_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                address_ = new java.util.ArrayList<com.auth0.protobuf.PeopleOuterClass.Address>();
                mutable_bitField0_ |= 0x00000002;
              }
              address_.add(
                  input.readMessage(com.auth0.protobuf.PeopleOuterClass.Address.parser(), extensionRegistry));
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                mobile_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              mobile_.add(s);
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                email_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              email_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          address_ = java.util.Collections.unmodifiableList(address_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          mobile_ = mobile_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          email_ = email_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.auth0.protobuf.PeopleOuterClass.internal_static_demo_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.auth0.protobuf.PeopleOuterClass.internal_static_demo_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.auth0.protobuf.PeopleOuterClass.Person.class, com.auth0.protobuf.PeopleOuterClass.Person.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 2;
    private java.util.List<com.auth0.protobuf.PeopleOuterClass.Address> address_;
    /**
     * <code>repeated .demo.Address address = 2;</code>
     */
    public java.util.List<com.auth0.protobuf.PeopleOuterClass.Address> getAddressList() {
      return address_;
    }
    /**
     * <code>repeated .demo.Address address = 2;</code>
     */
    public java.util.List<? extends com.auth0.protobuf.PeopleOuterClass.AddressOrBuilder> 
        getAddressOrBuilderList() {
      return address_;
    }
    /**
     * <code>repeated .demo.Address address = 2;</code>
     */
    public int getAddressCount() {
      return address_.size();
    }
    /**
     * <code>repeated .demo.Address address = 2;</code>
     */
    public com.auth0.protobuf.PeopleOuterClass.Address getAddress(int index) {
      return address_.get(index);
    }
    /**
     * <code>repeated .demo.Address address = 2;</code>
     */
    public com.auth0.protobuf.PeopleOuterClass.AddressOrBuilder getAddressOrBuilder(
        int index) {
      return address_.get(index);
    }

    public static final int MOBILE_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList mobile_;
    /**
     * <code>repeated string mobile = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMobileList() {
      return mobile_;
    }
    /**
     * <code>repeated string mobile = 3;</code>
     */
    public int getMobileCount() {
      return mobile_.size();
    }
    /**
     * <code>repeated string mobile = 3;</code>
     */
    public java.lang.String getMobile(int index) {
      return mobile_.get(index);
    }
    /**
     * <code>repeated string mobile = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBytes(int index) {
      return mobile_.getByteString(index);
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList email_;
    /**
     * <code>repeated string email = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getEmailList() {
      return email_;
    }
    /**
     * <code>repeated string email = 4;</code>
     */
    public int getEmailCount() {
      return email_.size();
    }
    /**
     * <code>repeated string email = 4;</code>
     */
    public java.lang.String getEmail(int index) {
      return email_.get(index);
    }
    /**
     * <code>repeated string email = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes(int index) {
      return email_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      for (int i = 0; i < address_.size(); i++) {
        output.writeMessage(2, address_.get(i));
      }
      for (int i = 0; i < mobile_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mobile_.getRaw(i));
      }
      for (int i = 0; i < email_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      for (int i = 0; i < address_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, address_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < mobile_.size(); i++) {
          dataSize += computeStringSizeNoTag(mobile_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMobileList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < email_.size(); i++) {
          dataSize += computeStringSizeNoTag(email_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getEmailList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.auth0.protobuf.PeopleOuterClass.Person)) {
        return super.equals(obj);
      }
      com.auth0.protobuf.PeopleOuterClass.Person other = (com.auth0.protobuf.PeopleOuterClass.Person) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getAddressList()
          .equals(other.getAddressList());
      result = result && getMobileList()
          .equals(other.getMobileList());
      result = result && getEmailList()
          .equals(other.getEmailList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getAddressCount() > 0) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddressList().hashCode();
      }
      if (getMobileCount() > 0) {
        hash = (37 * hash) + MOBILE_FIELD_NUMBER;
        hash = (53 * hash) + getMobileList().hashCode();
      }
      if (getEmailCount() > 0) {
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmailList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.auth0.protobuf.PeopleOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.auth0.protobuf.PeopleOuterClass.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Person)
        com.auth0.protobuf.PeopleOuterClass.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.auth0.protobuf.PeopleOuterClass.internal_static_demo_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.auth0.protobuf.PeopleOuterClass.internal_static_demo_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.auth0.protobuf.PeopleOuterClass.Person.class, com.auth0.protobuf.PeopleOuterClass.Person.Builder.class);
      }

      // Construct using com.auth0.protobuf.PeopleOuterClass.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddressFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        if (addressBuilder_ == null) {
          address_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          addressBuilder_.clear();
        }
        mobile_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.auth0.protobuf.PeopleOuterClass.internal_static_demo_Person_descriptor;
      }

      public com.auth0.protobuf.PeopleOuterClass.Person getDefaultInstanceForType() {
        return com.auth0.protobuf.PeopleOuterClass.Person.getDefaultInstance();
      }

      public com.auth0.protobuf.PeopleOuterClass.Person build() {
        com.auth0.protobuf.PeopleOuterClass.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.auth0.protobuf.PeopleOuterClass.Person buildPartial() {
        com.auth0.protobuf.PeopleOuterClass.Person result = new com.auth0.protobuf.PeopleOuterClass.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            address_ = java.util.Collections.unmodifiableList(address_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          mobile_ = mobile_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.mobile_ = mobile_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          email_ = email_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.email_ = email_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.auth0.protobuf.PeopleOuterClass.Person) {
          return mergeFrom((com.auth0.protobuf.PeopleOuterClass.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.auth0.protobuf.PeopleOuterClass.Person other) {
        if (other == com.auth0.protobuf.PeopleOuterClass.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (addressBuilder_ == null) {
          if (!other.address_.isEmpty()) {
            if (address_.isEmpty()) {
              address_ = other.address_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAddressIsMutable();
              address_.addAll(other.address_);
            }
            onChanged();
          }
        } else {
          if (!other.address_.isEmpty()) {
            if (addressBuilder_.isEmpty()) {
              addressBuilder_.dispose();
              addressBuilder_ = null;
              address_ = other.address_;
              bitField0_ = (bitField0_ & ~0x00000002);
              addressBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAddressFieldBuilder() : null;
            } else {
              addressBuilder_.addAllMessages(other.address_);
            }
          }
        }
        if (!other.mobile_.isEmpty()) {
          if (mobile_.isEmpty()) {
            mobile_ = other.mobile_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMobileIsMutable();
            mobile_.addAll(other.mobile_);
          }
          onChanged();
        }
        if (!other.email_.isEmpty()) {
          if (email_.isEmpty()) {
            email_ = other.email_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureEmailIsMutable();
            email_.addAll(other.email_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.auth0.protobuf.PeopleOuterClass.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.auth0.protobuf.PeopleOuterClass.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.auth0.protobuf.PeopleOuterClass.Address> address_ =
        java.util.Collections.emptyList();
      private void ensureAddressIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          address_ = new java.util.ArrayList<com.auth0.protobuf.PeopleOuterClass.Address>(address_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.auth0.protobuf.PeopleOuterClass.Address, com.auth0.protobuf.PeopleOuterClass.Address.Builder, com.auth0.protobuf.PeopleOuterClass.AddressOrBuilder> addressBuilder_;

      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public java.util.List<com.auth0.protobuf.PeopleOuterClass.Address> getAddressList() {
        if (addressBuilder_ == null) {
          return java.util.Collections.unmodifiableList(address_);
        } else {
          return addressBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public int getAddressCount() {
        if (addressBuilder_ == null) {
          return address_.size();
        } else {
          return addressBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public com.auth0.protobuf.PeopleOuterClass.Address getAddress(int index) {
        if (addressBuilder_ == null) {
          return address_.get(index);
        } else {
          return addressBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public Builder setAddress(
          int index, com.auth0.protobuf.PeopleOuterClass.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.set(index, value);
          onChanged();
        } else {
          addressBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public Builder setAddress(
          int index, com.auth0.protobuf.PeopleOuterClass.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.set(index, builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public Builder addAddress(com.auth0.protobuf.PeopleOuterClass.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.add(value);
          onChanged();
        } else {
          addressBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public Builder addAddress(
          int index, com.auth0.protobuf.PeopleOuterClass.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.add(index, value);
          onChanged();
        } else {
          addressBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public Builder addAddress(
          com.auth0.protobuf.PeopleOuterClass.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.add(builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public Builder addAddress(
          int index, com.auth0.protobuf.PeopleOuterClass.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.add(index, builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public Builder addAllAddress(
          java.lang.Iterable<? extends com.auth0.protobuf.PeopleOuterClass.Address> values) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, address_);
          onChanged();
        } else {
          addressBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          addressBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public Builder removeAddress(int index) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.remove(index);
          onChanged();
        } else {
          addressBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public com.auth0.protobuf.PeopleOuterClass.Address.Builder getAddressBuilder(
          int index) {
        return getAddressFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public com.auth0.protobuf.PeopleOuterClass.AddressOrBuilder getAddressOrBuilder(
          int index) {
        if (addressBuilder_ == null) {
          return address_.get(index);  } else {
          return addressBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public java.util.List<? extends com.auth0.protobuf.PeopleOuterClass.AddressOrBuilder> 
           getAddressOrBuilderList() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(address_);
        }
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public com.auth0.protobuf.PeopleOuterClass.Address.Builder addAddressBuilder() {
        return getAddressFieldBuilder().addBuilder(
            com.auth0.protobuf.PeopleOuterClass.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public com.auth0.protobuf.PeopleOuterClass.Address.Builder addAddressBuilder(
          int index) {
        return getAddressFieldBuilder().addBuilder(
            index, com.auth0.protobuf.PeopleOuterClass.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .demo.Address address = 2;</code>
       */
      public java.util.List<com.auth0.protobuf.PeopleOuterClass.Address.Builder> 
           getAddressBuilderList() {
        return getAddressFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.auth0.protobuf.PeopleOuterClass.Address, com.auth0.protobuf.PeopleOuterClass.Address.Builder, com.auth0.protobuf.PeopleOuterClass.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.auth0.protobuf.PeopleOuterClass.Address, com.auth0.protobuf.PeopleOuterClass.Address.Builder, com.auth0.protobuf.PeopleOuterClass.AddressOrBuilder>(
                  address_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }

      private com.google.protobuf.LazyStringList mobile_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMobileIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          mobile_ = new com.google.protobuf.LazyStringArrayList(mobile_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string mobile = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getMobileList() {
        return mobile_.getUnmodifiableView();
      }
      /**
       * <code>repeated string mobile = 3;</code>
       */
      public int getMobileCount() {
        return mobile_.size();
      }
      /**
       * <code>repeated string mobile = 3;</code>
       */
      public java.lang.String getMobile(int index) {
        return mobile_.get(index);
      }
      /**
       * <code>repeated string mobile = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMobileBytes(int index) {
        return mobile_.getByteString(index);
      }
      /**
       * <code>repeated string mobile = 3;</code>
       */
      public Builder setMobile(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMobileIsMutable();
        mobile_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mobile = 3;</code>
       */
      public Builder addMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMobileIsMutable();
        mobile_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mobile = 3;</code>
       */
      public Builder addAllMobile(
          java.lang.Iterable<java.lang.String> values) {
        ensureMobileIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mobile_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mobile = 3;</code>
       */
      public Builder clearMobile() {
        mobile_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string mobile = 3;</code>
       */
      public Builder addMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMobileIsMutable();
        mobile_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureEmailIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          email_ = new com.google.protobuf.LazyStringArrayList(email_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string email = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getEmailList() {
        return email_.getUnmodifiableView();
      }
      /**
       * <code>repeated string email = 4;</code>
       */
      public int getEmailCount() {
        return email_.size();
      }
      /**
       * <code>repeated string email = 4;</code>
       */
      public java.lang.String getEmail(int index) {
        return email_.get(index);
      }
      /**
       * <code>repeated string email = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes(int index) {
        return email_.getByteString(index);
      }
      /**
       * <code>repeated string email = 4;</code>
       */
      public Builder setEmail(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailIsMutable();
        email_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string email = 4;</code>
       */
      public Builder addEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailIsMutable();
        email_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string email = 4;</code>
       */
      public Builder addAllEmail(
          java.lang.Iterable<java.lang.String> values) {
        ensureEmailIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, email_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string email = 4;</code>
       */
      public Builder clearEmail() {
        email_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string email = 4;</code>
       */
      public Builder addEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureEmailIsMutable();
        email_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:demo.Person)
    }

    // @@protoc_insertion_point(class_scope:demo.Person)
    private static final com.auth0.protobuf.PeopleOuterClass.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.auth0.protobuf.PeopleOuterClass.Person();
    }

    public static com.auth0.protobuf.PeopleOuterClass.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public com.auth0.protobuf.PeopleOuterClass.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string street = 1;</code>
     */
    java.lang.String getStreet();
    /**
     * <code>optional string street = 1;</code>
     */
    com.google.protobuf.ByteString
        getStreetBytes();

    /**
     * <code>optional int32 number = 2;</code>
     */
    int getNumber();
  }
  /**
   * Protobuf type {@code demo.Address}
   */
  public  static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Address)
      AddressOrBuilder {
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      street_ = "";
      number_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Address(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              street_ = s;
              break;
            }
            case 16: {

              number_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.auth0.protobuf.PeopleOuterClass.internal_static_demo_Address_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.auth0.protobuf.PeopleOuterClass.internal_static_demo_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.auth0.protobuf.PeopleOuterClass.Address.class, com.auth0.protobuf.PeopleOuterClass.Address.Builder.class);
    }

    public static final int STREET_FIELD_NUMBER = 1;
    private volatile java.lang.Object street_;
    /**
     * <code>optional string street = 1;</code>
     */
    public java.lang.String getStreet() {
      java.lang.Object ref = street_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        street_ = s;
        return s;
      }
    }
    /**
     * <code>optional string street = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStreetBytes() {
      java.lang.Object ref = street_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        street_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBER_FIELD_NUMBER = 2;
    private int number_;
    /**
     * <code>optional int32 number = 2;</code>
     */
    public int getNumber() {
      return number_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStreetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, street_);
      }
      if (number_ != 0) {
        output.writeInt32(2, number_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStreetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, street_);
      }
      if (number_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, number_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.auth0.protobuf.PeopleOuterClass.Address)) {
        return super.equals(obj);
      }
      com.auth0.protobuf.PeopleOuterClass.Address other = (com.auth0.protobuf.PeopleOuterClass.Address) obj;

      boolean result = true;
      result = result && getStreet()
          .equals(other.getStreet());
      result = result && (getNumber()
          == other.getNumber());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + STREET_FIELD_NUMBER;
      hash = (53 * hash) + getStreet().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.auth0.protobuf.PeopleOuterClass.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.auth0.protobuf.PeopleOuterClass.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.auth0.protobuf.PeopleOuterClass.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Address)
        com.auth0.protobuf.PeopleOuterClass.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.auth0.protobuf.PeopleOuterClass.internal_static_demo_Address_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.auth0.protobuf.PeopleOuterClass.internal_static_demo_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.auth0.protobuf.PeopleOuterClass.Address.class, com.auth0.protobuf.PeopleOuterClass.Address.Builder.class);
      }

      // Construct using com.auth0.protobuf.PeopleOuterClass.Address.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        street_ = "";

        number_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.auth0.protobuf.PeopleOuterClass.internal_static_demo_Address_descriptor;
      }

      public com.auth0.protobuf.PeopleOuterClass.Address getDefaultInstanceForType() {
        return com.auth0.protobuf.PeopleOuterClass.Address.getDefaultInstance();
      }

      public com.auth0.protobuf.PeopleOuterClass.Address build() {
        com.auth0.protobuf.PeopleOuterClass.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.auth0.protobuf.PeopleOuterClass.Address buildPartial() {
        com.auth0.protobuf.PeopleOuterClass.Address result = new com.auth0.protobuf.PeopleOuterClass.Address(this);
        result.street_ = street_;
        result.number_ = number_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.auth0.protobuf.PeopleOuterClass.Address) {
          return mergeFrom((com.auth0.protobuf.PeopleOuterClass.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.auth0.protobuf.PeopleOuterClass.Address other) {
        if (other == com.auth0.protobuf.PeopleOuterClass.Address.getDefaultInstance()) return this;
        if (!other.getStreet().isEmpty()) {
          street_ = other.street_;
          onChanged();
        }
        if (other.getNumber() != 0) {
          setNumber(other.getNumber());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.auth0.protobuf.PeopleOuterClass.Address parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.auth0.protobuf.PeopleOuterClass.Address) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object street_ = "";
      /**
       * <code>optional string street = 1;</code>
       */
      public java.lang.String getStreet() {
        java.lang.Object ref = street_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          street_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string street = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStreetBytes() {
        java.lang.Object ref = street_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          street_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string street = 1;</code>
       */
      public Builder setStreet(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        street_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string street = 1;</code>
       */
      public Builder clearStreet() {
        
        street_ = getDefaultInstance().getStreet();
        onChanged();
        return this;
      }
      /**
       * <code>optional string street = 1;</code>
       */
      public Builder setStreetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        street_ = value;
        onChanged();
        return this;
      }

      private int number_ ;
      /**
       * <code>optional int32 number = 2;</code>
       */
      public int getNumber() {
        return number_;
      }
      /**
       * <code>optional int32 number = 2;</code>
       */
      public Builder setNumber(int value) {
        
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 number = 2;</code>
       */
      public Builder clearNumber() {
        
        number_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:demo.Address)
    }

    // @@protoc_insertion_point(class_scope:demo.Address)
    private static final com.auth0.protobuf.PeopleOuterClass.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.auth0.protobuf.PeopleOuterClass.Address();
    }

    public static com.auth0.protobuf.PeopleOuterClass.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Address(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    public com.auth0.protobuf.PeopleOuterClass.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_People_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_People_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/resources/people.proto\022\004demo\"" +
      "&\n\006People\022\034\n\006person\030\001 \003(\0132\014.demo.Person\"" +
      "U\n\006Person\022\014\n\004name\030\001 \001(\t\022\036\n\007address\030\002 \003(\013" +
      "2\r.demo.Address\022\016\n\006mobile\030\003 \003(\t\022\r\n\005email" +
      "\030\004 \003(\t\")\n\007Address\022\016\n\006street\030\001 \001(\t\022\016\n\006num" +
      "ber\030\002 \001(\005B\024\n\022com.auth0.protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_demo_People_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_People_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_People_descriptor,
        new java.lang.String[] { "Person", });
    internal_static_demo_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Person_descriptor,
        new java.lang.String[] { "Name", "Address", "Mobile", "Email", });
    internal_static_demo_Address_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_demo_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Address_descriptor,
        new java.lang.String[] { "Street", "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
